import = ["/home/takagi/.config/alacritty/rose-pine.toml"]
ipc_socket = false

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 19.5

[font.bold]
family = "JetBrainsMono NF SemiBold"

[font.normal]
family = "JetBrainsMono NF Light"
style = "Normal"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[shell]
program = "/usr/bin/fish"

[window]
dynamic_padding = true
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 12
y = 12
