[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#c0caf5"
yellow = "#e9b189"

[colors.cursor]
cursor = "#a9b1d6"
text = "#161821"

[colors.normal]
black = "#1e2132"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#a9b1d6"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#a9b1d6"

[colors.selection]
background = "#a9b1d6"
text = "#161821"
