# An array of paths to local repositories which are to be used as overrides for
# dependencies. For more information see the Cargo Guide.
# paths = ["/path/to/override"]

[cargo-new]
# This is your name/email to place in the `authors` section of a new Cargo.toml
# that is generated. If not present, then `git` will be probed, and if that is
# not present then `$USER` and `$EMAIL` will be used.
# name = "..."
# email = "..."

# By default `cargo new` will initialize a new git repository. This key can be
# set to `none` to disable this behavior.
vcs = "none"

# For the following sections, $triple refers to any valid target triple, not the
# literal string "$triple", and it will apply whenever that target triple is
# being compiled to.
[target]
# For Cargo builds which do not mention --target, this is the linker
# which is passed to rustc (via `-C linker=`). By default this flag is not
# passed to the compiler.
# linker = ".."

# [target.$triple]
# Similar to the above linker configuration, but this only applies to
# when the `$triple` is being compiled for.
# linker = ".."

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-args=-fuse-ld=/usr/bin/mold"]

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
ar = "/usr/i686-w64-mingw32/bin/ar"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "/usr/x86_64-w64-mingw32/bin/ar"

# Configuration keys related to the registry
[registry]
# index = "..."   # URL of the registry index (defaults to the central repository)
# token = "..."   # Access token (found on the central repo’s website)

[http]
# proxy = "..."     # HTTP proxy to use for HTTP requests (defaults to none)
# timeout = 60000   # Timeout for each HTTP request, in milliseconds

[build]
# jobs = 4                  # number of jobs to run by default (default to # cpus)
# rustc = "rustc"           # the rust compiler tool
# rustdoc = "rustdoc"       # the doc generator tool
# target = "triple"         # build for the target triple
# target-dir = "target"     # path of where to place all generated artifacts
# rustflags = ["..", ".."]  # custom flags to pass to all compiler invocations
rustc-wrapper = "sccache"

[term]
# verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output

# Network configuration
[net]
retry = 2 # number of times a network call will automatically retried
