[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"] }
ruff = { command = "ruff-lsp" }
typos = { command = "typos-lsp" }  # cargo install --git https://github.com/tekumara/typos-vscode
rust-analyzer.config = { check.command = "clippy" }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
# install `pyright` and `ruff-lsp`
language-servers = ["pyright", "ruff", "typos"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "ini"
file-types = [
  "desktop",
  "conf",
  
  # from default setting
  "ini",
  # Systemd unit files
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network"
]
indent = { tab-width = 4, unit = "    " }
language-servers = ["typos"]

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "git-commit"
language-servers = ["typos"]
