[colors]

# Normal colors
foreground       = '#f2f4f8'
background       = '#161616'
black            = '#282828'
blue             = '#78a9ff'
cursor           = '#be95ff'
cyan             = '#33b1ff'
green            = '#25be6a'
magenta          = '#be95ff'
red              = '#ee5396'
white            = '#dfdfe0'
yellow           = '#08bdba'

# UI colors
tabs             = '#6e6f70'
tabs-active      = '#78a9ff'
selection-foreground = '#2a2a2a'
selection-background = '#f2f4f8'

# Light colors
light-black      = '#484848'
light-blue       = '#8cb6ff'
light-cyan       = '#52bdff'
light-foreground = '#c8a5ff'
light-green      = '#46c880'
light-magenta    = '#c8a5ff'
light-red        = '#f16da6'
light-white      = '#e4e4e5'
light-yellow     = '#2dc7c4'
