[colors]
background = '#181616'
foreground = '#c5c9c5'
selection-background = '#49473e'
selection-foreground = '#ddd8bb'
cursor = '#e6e0c2'
black = '#181616'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#c292a5'
cyan = '#8ea4a2'
white = '#c8c093'
light_black = '#a6a69c'
light_red = '#e46876'
light_green = '#87a987'
light_yellow = '#e6c384'
light_blue = '#7fb4ca'
light_magenta = '#938aa9'
light_cyan = '#7aa89f'
light_white = '#c5c9c5'
