[colors]
background       = '#191724'
black            = '#26233a'
blue             = '#9ccfd8'
cursor           = '#524f67'
cyan             = '#ebbcba'
foreground       = '#e0def4'
green            = '#31748f'
magenta          = '#c4a7e7'
red              = '#eb6f92'
tabs             = '#494c62'
tabs-active      = '#6a6e8e'
white            = '#e0def4'
yellow           = '#f6c177'
dim-black        = '#6e6a86'
dim-blue         = '#9ccfd8'
dim-cyan         = '#ebbcba'
dim-foreground   = '#908caa'
dim-green        = '#31748f'
dim-magenta      = '#c4a7e7'
dim-red          = '#eb6f92'
dim-white        = '#e0def4'
dim-yellow       = '#f6c177'
light-black      = '#6e6a86'
light-blue       = '#9ccfd8'
light-cyan       = '#ebbcba'
light-foreground = '#e0def4'
light-green      = '#31748f'
light-magenta    = '#c4a7e7'
light-red        = '#eb6f92'
light-white      = '#e0def4'
light-yellow     = '#f6c177'
