#! /bin/sh

### Auto startup
pgrep -x sxhkd > /dev/null || sxhkd &

# numlock on
numlockx on &

# unlock kwallet
/usr/lib/pam_kwallet_init &

# display power management
xset s off &
xset dpms 0 0 1200 &

# screen locker
pgrep -x xautolock > /dev/null || xautolock -time 5 locker "$HOME/.config/i3/lock.sh" &

# redshift
pgrep -x redshift > /dev/null || redshift -l ${LATITUDE}:${LONGITUDE} &

# launch polybar
$HOME/.config/polybar/launch.sh &

# clipboard manager
pgrep -x klipper > /dev/null || klipper &

# dunst notifier
pgrep -x dunst > /dev/null || dunst &

# fcitx input method
pgrep -x fcitx > /dev/null || fcitx &

# easystroke (mouse gesture)
pgrep -x easystroke > /dev/null || easystroke &

# set wallpaper
feh --bg-scale $HOME/.config/i3/bg.jpg &

# keyboard
$HOME/.config/i3/keyboard.sh &

### Set workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

### Set windows
bspc config border_width         0
bspc config top_padding         24
bspc config bottom_padding      -8
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Set rules
bspc rule -a Rofi focus=on
bspc rule -a Screenkey manage=off
