#!/usr/bin/env zsh

### Auto startup
autostart &

CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

### Set scrachpad terminal
i3_config=$CONFIG_HOME/i3/config
if grep -q "gaps" $i3_config; then
  rectangle=938x1028+966+40
else
  rectangle=960x1056+960+24
fi
bspc rule -a Alacritty:scratchterm state=floating sticky=on hidden=on rectangle=$rectangle

### Set workspaces
bspc monitor -d 1 2 3 4 5 6

### Set windows
if grep -q "gaps" $i3_config; then
  border=2
  top=28
  bottom=-6
  gap=12
else
  border=0
  top=24
  bottom=0
  gap=0
fi

bspc config border_width    $border
bspc config top_padding        $top
bspc config bottom_padding  $bottom
bspc config window_gap         $gap
bspc config split_ratio        0.50

bspc config normal_border_color "#018291"
bspc config active_border_color "#434445"
bspc config focused_border_color "#9809a2"

bspc config borderless_monocle false
bspc config gapless_monocle   false

### Set rules
bspc rule -a Rofi focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=4

# FFXIV benchmark
bspc rule -a ffxiv-shadowbringers-bench.exe state=floating center=on
bspc rule -a ffxiv_dx11.exe state=floating center=on

# steam games (proton games seems to be floated by default)
bspc rule -a Helltaker.x86_64 state=floating center=on
bspc rule -a helltaker.x86_64 state=floating center=on
bspc rule -a steam_app_359870 state=floating  # FFX/FFX-II launcher

# looking-glass
bspc rule -a looking-glass-client state=floating center=on
