#!/usr/bin/env zsh

### Auto startup
autostart &

CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

### Set scrachpad terminal
i3_config=$CONFIG_HOME/i3/config
if grep "gaps" $i3_config > /dev/null; then
  rectangle=936x1032+968+40
else
  rectangle=960x1056+960+24
fi
bspc rule -a scratchkitty state=floating sticky=on hidden=on rectangle=$rectangle

### Set workspaces
bspc monitor -d 1 2 3 4 5 6

### Set windows
if grep "gaps" $i3_config > /dev/null; then
  border=2
  bottom=-8
  gap=16
else
  border=0
  bottom=0
  gap=0
fi

bspc config border_width    $border
bspc config top_padding          24
bspc config bottom_padding  $bottom
bspc config window_gap         $gap
bspc config split_ratio        0.50

bspc config normal_border_color "#323334"
bspc config active_border_color "#434445"
bspc config focused_border_color "#5fd7af"

bspc config borderless_monocle true
bspc config gapless_monocle   false

### Set rules
bspc rule -a Rofi focus=on
bspc rule -a Screenkey manage=off

# set border rules
bspc rule -a firefox-game border=off
bspc rule -a discord border=off

# steam games (proton games seems to be floated by default)
bspc rule -a Helltaker.x86_64 state=floating center=on
bspc rule -a helltaker.x86_64 state=floating center=on

# looking-glass
bspc rule -a looking-glass-client state=floating center=on
