[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""

[[block]]
block = "custom"
command = "ff-volume-check"
interval = 1
on_click = "ff-volume-fix"

[[block]]
block = "music"
interface_name_exclude = []
max_width = 70
dynamic_width = true
marquee_interval = 3
marquee_speed = 0.5
buttons = ["prev", "play", "next"]
hide_when_empty = false
format = " [{avail}] {player}: {combo} "
[block.theme_overrides]
info_fg = "#c74ded"
info_bg = "#161925"

[[block]]
block = "cpu"
format = '<span color="#c74ded99" font_family="Fira Code">{barchart}</span> {utilization}'
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 1

[[block]]
block = "custom"
command = '''printf '{"icon": "gpu", "text":"%2d%%"}' $(cat /sys/class/drm/card0/device/gpu_busy_percent | tr -d "[:alpha:].'\-")'''
interval = 1
json = true

[[block]]
block = "time"
interval = 0.5
format = "%a %d %b %Y  %H:%M:%S"

[[block]]
block = "pacman"
interval = 3600
aur_command = "yay -Qum"
format = "{both}"
format_singular = "{both}"
hide_when_uptodate = true
[block.theme_overrides]
info_fg = "#161925"
info_bg = "#c74ded"
