[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""
weather_thunder = ""

[[block]]
block = "custom"
command = "echo ''"
interval = "once"
[block.theme_overrides]
idle_fg = "#20bbfc"

[[block]]
block = "music"
interface_name_exclude = ["firefox", "chromium"]
max_width = 60
dynamic_width = true
marquee_interval = 10
marquee_speed = 0.5
buttons = ["prev", "play", "next"]
hide_when_empty = false
format = " [{avail}] {player}: {combo} "
[block.theme_overrides]
info_fg = "#c74ded"
info_bg = "#161925"

[[block]]
block = "custom"
command = "ff-volume-check"
interval = 1
on_click = "ff-volume-fix"

[[block]]
block = "cpu"
format = '<span color="#c74ded99" font_family="unifont">{barchart}</span> {utilization}'
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 1

[[block]]
block = "custom"
command = '''printf '{"icon": "gpu", "text":"%2d%%"}' $(cat /sys/class/drm/card0/device/gpu_busy_percent | tr -d "[:alpha:].'\-")'''
interval = 1
json = true

[[block]]
block = "temperature"
collapsed = false
inputs = [
  # CPU temperatures
  "Package id 0", "Core 0", "Core 1", "Core 2", "Core 3", "Core 4", "Core 5",
  # GPU temperatures
  "edge", "junction", "mem",
]
format = "{max}C"
[block.theme_overrides]
warning_fg = "#c74ded"
warning_bg = "#161925"
critical_fg = "#161925"
critical_bg = "#ed254e"

[[block]]
block = "time"
interval = 0.5
format = "%a %d %b %Y  %H:%M:%S"

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"
format = "{both}"
format_singular = "{both}"
hide_when_uptodate = true
[block.theme_overrides]
info_fg = "#161925"
info_bg = "#c74ded"

[[block]]
# block to show the number of systemd failures
block = "custom"
interval = 600
json = true
command = '''printf '{"icon": "weather_thunder", "state": "Warning", "text": "%s"}' $(systemctl --state=failed -q | wc -l | tr -d 0)'''
hide_when_empty = true
[block.theme_overrides]
warning_fg = "#161925"
warning_bg = "#f9dc5c"
