[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""
music = "  "

[[block]]
block = "custom"
json = true
command = "sway-idle-watch"
interval = 1
on_click = "sway-idle-toggle"
[block.theme_overrides]
idle_fg = "#aeb3bb"  # comment color
info_fg = "#bf616a"  # red

[[block]]
block = "custom"
command = "ff-volume-watch"
interval = 0.5
on_click = "ff-volume-toggle"

[[block]]
block = "music"
player = ["spotify", "audacious"]
max_width = 120
dynamic_width = true
marquee_interval = 10
marquee_speed = 0.5
buttons = ["prev", "play", "next"]
hide_when_empty = false
format = '{combo} '
[block.theme_overrides]
info_fg = "#8fbcbb"  # cyan

[[block]]
block = "time"
interval = 0.25
format = "%a %d %b %Y  %H:%M:%S"
