[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""

[[block]]
block = "custom"
json = true
command = "sway-idle-watch"
interval = 1
on_click = "sway-idle-toggle"
[block.theme_overrides]
idle_fg = "#7c7c7c"
info_fg = "#ed254e"

[[block]]
block = "custom"
command = "ff-volume-watch"
interval = 0.5
on_click = "ff-volume-toggle"

[[block]]
block = "music"
player = ["spotify"]
max_width = 120
dynamic_width = true
marquee_interval = 10
marquee_speed = 0.5
buttons = ["prev", "play", "next"]
hide_when_empty = false
format = ' {player}: {combo} '
[block.theme_overrides]
info_fg = "#c74ded"

[[block]]
block = "time"
interval = 0.25
format = "%a %d %b %Y  %H:%M:%S"
