[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""

# [[block]]
# # empty block just to show left-side separator
# block = "custom"
# command = "echo ''"
# interval = "once"
# [block.theme_overrides]
# # transparent foreground
# idle_fg = "#0000000"

[[block]]
block = "custom"
command = "ff-volume-watch"
interval = 0.5
on_click = "ff-volume-toggle"

[[block]]
block = "music"
player = ["mpd", "spotifyd"]
max_width = 120
dynamic_width = true
marquee_interval = 10
marquee_speed = 0.5
buttons = ["prev", "play", "next"]
hide_when_empty = false
#on_click = "if [ $(mpc status %state%) = 'playing' ]; then mpc stop; else mpc play; fi"
format = ' {player}: {combo} '
[block.theme_overrides]
info_fg = "#c74ded"

[[block]]
block = "time"
interval = 0.25
format = "%a %d %b %Y  %H:%M:%S"
