[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
json = true
command = "sway-idle-watch"
interval = 1
[[block.click]]
button = "left"
cmd = "sway-idle-toggle"
[block.theme_overrides]
idle_fg = "#6e738d"  # comment color
info_fg = "#ed8796"  # red

[[block]]
block = "custom"
json = true
command = "ff-volume-watch"
interval = "once"
persistent = true
[[block.click]]
button = "left"
cmd = "ff-volume-toggle"

[[block]]
block = "music"
player = ["spotify", "audacious"]
format = '   {$combo.str(max_w:120, rot_interval:0.5) $prev $play $next |}'
[[block.click]]
button = "up"
cmd = "playerctl previous"
[[block.click]]
button = "down"
cmd = "playerctl next"
[block.theme_overrides]
info_fg = "#c6a0f6"  # cyan

[[block]]
block = "time"
interval = 0.25
format = "   $timestamp.datetime(f:'%a %d %b %Y') 󰅐  $timestamp.datetime(f:'%H:%M:%S') "
