[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
json = true
command = "idle-watch"
interval = 1
[[block.click]]
button = "left"
cmd = "idle-toggle"
[block.theme_overrides]
idle_fg = "#6e6f70"  # comment
info_fg = "#ee5396"  # red

[[block]]
block = "custom"
command = "mic-mute-watch"
json = true
interval = 0.5
[[block.click]]
button = "left"
cmd = "mic-mute-toggle"
[block.theme_overrides]
idle_fg = "#6e6f70"  # comment
info_fg = "#ee5396"  # red

[[block]]
block = "custom"
json = true
command = "ff-volume-watch"
interval = "once"
persistent = true
[[block.click]]
button = "left"
cmd = "ff-volume-toggle"
[block.theme_overrides]
idle_fg = "#6e6f70"  # comment
info_fg = "#ee5396"  # red

[[block]]
block = "music"
player = ["spotify", "mpd"]
format = '   {$combo.str(max_w:120, rot_interval:0.5)   $prev $play $next |}'
[[block.click]]
button = "left"
cmd = "playerctl play-pause"
[[block.click]]
button = "up"
cmd = "playerctl previous"
[[block.click]]
button = "down"
cmd = "playerctl next"
[block.theme_overrides]
info_fg = "#33b1ff"  # cyan

[[block]]
block = "time"
interval = 1
format = "   $timestamp.datetime(f:'%a %d %b %Y') 󰅐 $timestamp.datetime(f:'%H:%M:%S') "
