[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
time = ""
weather_thunder = ""

[[block]]
block = "custom"
command = "mic-mute-watch"
json = true
interval = 0.5
on_click = "mic-mute-toggle"
[block.theme_overrides]
idle_fg = "#999999"
info_fg = "#ed254e"

[[block]]
block = "cpu"
format = '<span color="#5dda92" font_family="unifont">{barchart}</span> {utilization}'
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 1

[[block]]
block = "custom"
command = '''printf '{"icon": "gpu", "text":"%2d%%"}' $(cat /sys/class/drm/card0/device/gpu_busy_percent | tr -d "[:alpha:].'\-")'''
interval = 1
json = true

[[block]]
block = "temperature"
collapsed = false
info = 64
inputs = [
  # CPU temperatures
  "Package id 0",
  "Core 0",
  "Core 1",
  "Core 2",
  "Core 3",
  "Core 4",
  "Core 5",

  # GPU temperatures
  "edge",
  #"junction",
  "mem",
]
format = "{max}C"
[block.theme_overrides]
warning_fg = "#ff1493"
critical_fg = "#000000"
critical_bg = "#ed254e"

[[block]]
block = "time"
interval = 0.2
format = "%a %d %b %Y  %H:%M:%S"

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"
format = "{both}"
format_singular = "{both}"
hide_when_uptodate = true
[block.theme_overrides]
info_fg = "#000000"
info_bg = "#c74ded"

[[block]]
# block to show the number of systemd failures
block = "custom"
interval = 60
json = true
command = '''printf '{"icon": "weather_thunder", "state": "Warning", "text": "%s"}' $(echo "$(($(systemctl --state=failed -q | wc -l)+$(systemctl --user --state=failed -q | wc -l)))" | tr -d 0)'''
hide_when_empty = true
[block.theme_overrides]
warning_fg = "#000000"
warning_bg = "#f9dc5c"
