[theme]
theme = "native"

[icons]
icons = "material-nf"
[icons.overrides]
weather_thunder = ""  # error icon

[[block]]
block = "custom"
command = "mic-mute-watch"
json = true
interval = 0.5
[[block.click]]
button = "left"
cmd = "mic-mute-toggle"
[block.theme_overrides]
idle_fg = "#6c7086"  # comment color
info_fg = "#f38ba8"  # red

[[block]]
block = "cpu"
format = '<span color="#cba6f7">$barchart</span> $utilization'
interval = 1

[[block]]
# CPU temperature
block = "custom"
command = "temperature cpu state"
interval = 1
json = true
[block.theme_overrides]
warning_fg = "#f38ba8"  # red
critical_fg = "#000000"
critical_bg = "#f38ba8"  # red

[[block]]
block = "memory"
format = "   $mem_used_percents.eng(w:2)"
interval = 1

[[block]]
# GPU
block = "custom"
command = '''printf '{"icon": "gpu", "text":"%2d%%"}' $(cat /sys/class/drm/card0/device/gpu_busy_percent | tr -d "[:alpha:].'\-")'''
interval = 1
json = true

[[block]]
# GPU temperature
block = "custom"
command = "temperature gpu state"
interval = 1
json = true
[block.theme_overrides]
warning_fg = "#f38ba8"  # red
critical_fg = "#000000"
critical_bg = "#f38ba8"  # red

[[block]]
block = "time"
interval = 1
format = "   $timestamp.datetime(f:'%a %d %b %Y') 󰅐 $timestamp.datetime(f:'%H:%M:%S') "

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"
format = " 󰇚 $both "
format_singular = " 󰇚 $both "
format_up_to_date = ""
[block.theme_overrides]
info_fg = "#000000"
info_bg = "#cba6f7"  # mauve

[[block]]
# block to show the number of systemd failures
block = "custom"
interval = 60
# json = true
# command = '''printf '{"icon": "weather_thunder", "state": "Warning", "text": "%s"}' $(echo "$(($(systemctl --state=failed -q | wc -l)+$(systemctl --user --state=failed -q | wc -l)))" | tr -d 0)'''
command = '''echo $(($(systemctl --state=failed -q | wc -l)+$(systemdctl --user --state=failed -q | wc -l))) | tr -d 0'''
hide_when_empty = true
[block.theme_overrides]
idle_fg = "#000000"
idle_bg = "#f9e2af"  # yellow
