[theme]
name = "native"

[icons]
name = "material-nf"
[icons.overrides]
memory = ""
time = ""
weather_thunder = ""

[[block]]
block = "custom"
command = "mic-mute-watch"
json = true
interval = 0.5
on_click = "mic-mute-toggle"
[block.theme_overrides]
idle_fg = "#aeb3bb"  # comment color
info_fg = "#bf616a"  # red

[[block]]
block = "cpu"
format = '<span color="#66cccc" font_family="unifont">{barchart}</span> {utilization}'
interval = 1

[[block]]
# CPU temperature
block = "custom"
command = "temperature cpu state"
interval = 1
json = true
[block.theme_overrides]
warning_fg = "#bf616a"  # red
critical_fg = "#000000"
critical_bg = "#bf616a"  # red

[[block]]
block = "memory"
display_type = "memory"
icons_format = " "
format_mem = " {mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 1

[[block]]
# GPU
block = "custom"
command = '''printf '{"icon": "gpu", "text":"%2d%%"}' $(cat /sys/class/drm/card0/device/gpu_busy_percent | tr -d "[:alpha:].'\-")'''
interval = 1
json = true

[[block]]
# GPU temperature
block = "custom"
command = "temperature gpu state"
interval = 1
json = true
[block.theme_overrides]
warning_fg = "#bf616a"  # red
critical_fg = "#000000"
critical_bg = "#bf616a"  # red

[[block]]
block = "time"
interval = 0.2
format = "%a %d %b %Y  %H:%M:%S"

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"
format = "{both}"
format_singular = "{both}"
hide_when_uptodate = true
[block.theme_overrides]
info_fg = "#000000"
info_bg = "#b48ead"  # magenta

[[block]]
# block to show the number of systemd failures
block = "custom"
interval = 60
json = true
command = '''printf '{"icon": "weather_thunder", "state": "Warning", "text": "%s"}' $(echo "$(($(systemctl --state=failed -q | wc -l)+$(systemctl --user --state=failed -q | wc -l)))" | tr -d 0)'''
hide_when_empty = true
[block.theme_overrides]
warning_fg = "#000000"
warning_bg = "#ebcb8b"  # yellow
