# Nordfox Dark Theme for Helix Editor
# Original Author : RayGervais<raygervais@hotmail.ca>

"ui.linenr.selected" = "nord4"
"ui.cursorline.primary" = { bg = "nord1" }
"ui.text.focus" = { fg = "nord8", modifiers = ["bold"] }
"ui.menu" = { fg = "nord6", bg = "nord1" }
"ui.menu.selected" = { fg = "nord8", bg = "nord2" }
"ui.virtual.ruler" = { bg = "nord1" }

"info" = "nord8"
"hint" = "nord8"

# Polar Night
# nord0 - background color
"ui.background" = { bg = "nord0" }

"ui.statusline.inactive" = { fg = "nord8", bg = "nord1" }
"ui.statusline.normal" = { fg = "nord0", bg = "nord8" }
"ui.statusline.insert" = { fg = "nord0", bg = "nord13" }
"ui.statusline.select" = { fg = "nord0", bg = "nord15" }

# nord1 - status bars, panels, modals, autocompletion
"ui.statusline" = { fg = "nord4", bg = "nord1" }
"ui.popup" = { bg = "nord1" }
"ui.window" = { bg = "nord1" }
"ui.help" = { bg = "nord1", fg = "nord4" }

# nord2 - active line, highlighting
"ui.selection" = { bg = "nord2" }
"ui.cursor.match" = { bg = "nord2" }

# nord3 - comments, invisible/non-printable characters
"comment" = { fg = "comment", modifiers = ["italic"] }
"ui.linenr" = "nord3_bright"
"ui.virtual.whitespace" = "nord3_bright"

# Snow Storm
# nord4 - cursor, variables, constants, attributes, fields
"ui.cursor.primary" = { fg = "nord4", modifiers = ["reversed"] }
"attribute" = "nord4"
"variable" = "fg0"
"constant" = "orange"
"variable.builtin" = "red"
"constant.builtin" = "red"
"namespace" = "cyan"

# nord5 - subtle UI text

# nord6 - base text, punctuation
"ui.text" = "nord6"
# "punctuation" = "nord6"

# Frost
# nord7 - classes, types, primitives
"type" = "yellow"
"type.builtin" = "cyan"
"label" = "nord7"

# nord8 - declaration, methods, routines
"constructor" = "nord8"
"function" = "blue"
"function.macro" = "orange"
"punctuation.special" = "orange"
"function.builtin" = "red"

# nord9 - operator, tags, units, punctuations
"punctuation.delimiter" = "nord9"
#"punctuation.bracket" = "red"
"operator" = "fg2"
"variable.other.member" = "nord9"

# nord10 - keywords, special
"keyword" = "magenta"
"keyword.directive" = "magenta"
"variable.parameter" = "cyan"

# Aurora
# nord11 - error
"error" = "nord11"

# nord12 - annotations, decorators
"special" = "nord12"
"module" = "pink"

# nord13 - warnings, escape characters, regex
"warning" = "nord13"
"constant.character.escape" = "nord13"

# nord14 - strings
"string" = "nord14"

# nord15 - integer, floating point
"constant.numeric" = "nord15"

# markup
"markup.heading" = "nord8"
"markup.list" = "nord9"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.text" = "nord8"
"markup.raw" = "nord7"

# lsp diagnostics
"diagnostic.error" = { underline = { color = "nord11", style = "curl" } }
"diagnostic.warning" = { underline = { color = "nord13", style = "curl" } }
"diagnostic.info" = { underline = { color = "nord8", style = "curl" } }
"diagnostic.hint" = { underline = { color = "nord8", style = "curl" } }

# vcs
"diff.plus" = "nord14"
"diff.delta" = "nord12"
"diff.minus" = "nord11"

### Syntax highlighting
"none" = { fg = "orange" }
"include" = { fg = "pink" }
"from" = { fg = "pink" }
"import" = { fg = "pink" }


[palette]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
# we use a brighter nord3 based on discussion here:
# https://github.com/arcticicestudio/nord/issues/94
nord3_bright = "#616e88"
nord4 = "#d8dee9"
nord6 = "#eceff4"
#nord7 = "#8fbcbb"
nord7 = "#93ccdc"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
#nord10 = "#5e81ac"
nord10 = "#668aab"
nord11 = "#bf616a"
#nord12 = "#d08770"
nord12 = "#d06f79"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"

black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
orange = "#c9826b"
pink = "#d092ce"

comment = "#60728a"

bg0 = "#232831"  # Dark bg (status line and float)
bg1 = "#2e3440"  # Default bg
bg2 = "#39404f"  # Lighter bg (colorcolm folds)
bg3 = "#444c5e"  # Lighter bg (cursor line)
bg4 = "#5a657d"  # Conceal, border fg

fg0 = "#c7cdd9"  # Lighter fg
fg1 = "#cdcecf"  # Default fg
fg2 = "#abb1bb"  # Darker fg (status line)
fg3 = "#7e8188"  # Darker fg (line numbers, fold colums)

sel0 = "#3e4a5b"  # Popup bg, visual selection bg
sel1 = "#4f6074"  # Popup sel bg, search bg
