[[entries]]
name = "Brave Search"
default = true
url = "https://search.brave.com/search?q=%TERM%"
icon = "brave"
prefix = "/"

[[entries]]
name = "Google Search"
default = false
url = "https://www.google.com/search?q=%TERM%"
icon = "google"

[[entries]]
name = "Bing Search"
default = false
url = "https://www.bing.com/search?q=%TERM%"
icon = "microsoft"
