#!/usr/bin/env zsh
# ============================================
#  Zsh Environment Variables
# ============================================

# Set default environment variables
export XDG_CONFIG_HOME=$HOME/.config
export XDG_PICTURES_DIR=$HOME/Pictures
export EDITOR=vim
export LESS="-iFRS"
if which vimpager > /dev/null 2>&1; then
  export MANPAGER=vimpager
fi

# OS setting
if [[ "$(uname)" == "Darwin" ]]; then
  export OSNAME=Mac
elif [[ $OSTYPE == msys ]]; then
  export OSNAME=Windows
elif [[ "$(expr substr $(uname -s) 1 4)" == "MSYS" ]]; then
  export OSNAME=Windows
elif [[ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]]; then
  export OSNAME=Windows
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
  if [ -e /etc/arch-release ]; then
    export OSNAME=Arch
  elif [ -e /etc/lsb-release ]; then
    export OSNAME=Ubuntu
  else
    export OSNAME=Linux
  fi
else
  export OSNAME=Unknown
fi

# kitty is not supported in vagrant-ubuntu
if [[ "$OSNAME" == "Ubuntu" && "$USERNAME" == "vagrant" && "$TERM" == "xterm-kitty" ]]; then
  export TERM=xterm-256color
fi

# Set locale
if [[ $TERM == cygwin ]]; then
  export LANG=en_US.utf-8
fi

# Project setting
export PROJECT_HOME=$HOME/Projects
if [[ $OSNAME == Ubuntu ]]; then
  export WORKON_HOME=$HOME/.virtualenvs/ubuntu
elif [[ $OSNAME == Arch ]]; then
  export WORKON_HOME=$HOME/.virtualenvs/arch
elif [[ $OSTYPE == msys ]]; then
  export WORKON_HOME=$HOME/.virtualenvs/msys
elif [[ $OSTYPE == cygwin ]]; then
  export WORKON_HOME=$HOME/.virtualenvs/cygwin
else
  export WORKON_HOME=$HOME/.virtualenvs
fi

# Setting $PATH
function add_path() {
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      path=("$1" $path)
  esac
}

# Nix
if [[ -f $HOME/.nix-profile/etc/profile.d/nix.sh ]]; then
  . $HOME/.nix-profile/etc/profile.d/nix.sh
fi

if [[ $OSNAME == Windows ]]; then
  export MSYS2_PATH_TYPE=inherit
  add_path /mingw64/bin
fi

if [[ $OSNAME == Mac ]]; then
  add_path /usr/local/sbin
  add_path /usr/local/bin
fi

if [[ $OSNAME == Ubuntu ]]; then
  # ubuntu specific binaries
  add_path $HOME/bin/ubuntu

  # go
  export GOROOT=/usr/local/go
  add_path $GOROOT/bin

  # nim
  add_path $HOME/.nimble/bin

  # node
  add_path $HOME/opt/node/bin

  # pyenv
  export PYENV_ROOT="$HOME/.pyenv"
  add_path $PYENV_ROOT/bin
fi

# pyenv
if which pyenv >/dev/null 2>&1; then
  add_path "$(pyenv root)/shims"
fi

# pip --user
if [[ $OSNAME == Mac ]]; then
  add_path $HOME/Library/Python/3.7/bin
else
  add_path $HOME/.local/bin
fi

# rust
add_path $HOME/.cargo/bin
if which rustc > /dev/null 2>&1; then
  export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi
if which sccache > /dev/null 2>&1; then
  export RUSTC_WRAPPER=$(which sccache)
fi

# go
export GOPATH=$HOME/.go
add_path $GOPATH/bin

# nvm
export NVM_DIR=$HOME/.nvm

# npm
add_path $HOME/.node_modules/bin
export npm_config_prefix=~/.node_modules

# user local scripts
add_path $HOME/bin

# load machine local profile
[[ -f $ZDOTDIR/.zshenv.local ]] && source $ZDOTDIR/.zshenv.local

# vim: sw=2 et
