# vim: ft=conf

# Colors (tokyonight - night)
set $foreground  #c6c8d1
set $background  #161821
set $transparent #00000000
set $black       #1e2132
set $red         #e27878
set $green       #b4b382
set $yellow      #e2a478
set $blue        #84a0c6
set $magenta     #a093c7
set $cyan        #89b8c2
set $white       #c6c8d1

# semi-transparent colors
set $green2      #b4b382bb
set $magenta2    #a093c7bb
set $cyan2       #89b8c2bb

