# vim: ft=conf

# Colors (tokyonight - night)
set $foreground  #bbbbbb
set $background  #121212
set $transparent #00000000
set $black       #121212
set $red         #fa2573
set $green       #98e123
set $yellow      #dfd460
set $blue        #1080d0
set $magenta     #8700ff
set $cyan        #43a8d0
set $white       #bbbbbb

# semi-transparent colors
set $green2      #98e123bb
set $magenta2    #8700ffbb
set $cyan2       #32a8d0bb

