# vim: ft=conf

# Colors (tokyonight - night)
set $foreground  #f7f7f7
set $background  #1b1b1b
set $transparent #00000000
set $black       #1b1b1b
set $red         #b84131
set $green       #7da900
set $yellow      #c4a500
set $blue        #62a3c4
set $magenta     #ba8acc
set $cyan        #207383
set $white       #f7f7f7

# semi-transparent colors
set $green2      #7da900bb
set $yellow2     #c4a500bb
set $magenta2    #ba8accbb
set $cyan2       #207383bb
