# vim: ft=conf

# Colors (tokyonight - night)
set $foreground  #c0caf5
set $background  #1a1b26
set $transparent #00000000
set $black       #15161e
set $red         #f7768e
set $green       #9ece6a
set $yellow      #e0af68
set $blue        #7aa2f7
set $magenta     #bb9af7
set $cyan        #7dcfff
set $white       #a9b1d6

# semi-transparent colors
set $green2      #9ece6abb
set $magenta2    #bb9af7bb
set $cyan2       #7dcfffbb

