#!/usr/bin/bash

# ### Start fish if login shell on tty
# if type fish &>/dev/null && shopt -q login_shell; then
#   if [ -z "$ZELLIJ" ] && [ -n "$SSH_TTY" ] && type zellij &>/dev/null; then
#     export SHELL=/usr/bin/fish
#     if zellij ls &>/dev/null; then
#       exec zellij a
#     else
#       exec zellij -s session_name
#     fi
#   else
#     exec fish
#   fi
# fi
#
# ===> Moved to local config


### Load local settings
test -f "${HOME}/.bashrc.local" && source "${HOME}/.bashrc.local"

### atuin
if type atuin &>/dev/null; then
  eval "$(atuin init bash --disable-up-arrow)"
fi

### direnv
if type direnv &>/dev/null; then
  eval "$(direnv hook bash)"
fi

### zoxide
if type zoxide &>/dev/null; then
  eval "$(zoxide init bash)"
fi

### Prompt
if [[ $TERM != "dumb" ]] && type starship &>/dev/null; then
  eval "$(starship init bash --print-full-init)"
fi

# vim: sw=2 et ft=bash
