#!/usr/bin/bash

# ============================================
# Environment Variables
# ============================================

# XDG Data bin PATH
export PATH="$HOME/.local/bin:$PATH"

# Go
export GOPATH="$HOME/.go"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
if type rustc &>/dev/null; then
  RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
  export RUST_SRC_PATH
fi
if type sccache &>/dev/null; then
  RUSTC_WRAPPER=$(which sccache)
  export RUSTC_WRAPPER
fi

# Add user specific bin dir
export PATH="$HOME/bin:$PATH"

# set default programs as nvim
if type nvim &>/dev/null; then
  export EDITOR=nvim
  export MANPAGER="nvim +Man! -u ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/manrc"
elif type vim &>/dev/null; then
  export EDITOR=vim
fi

# Set less variables
export LESS="-iFRS"
export SYSTEMD_LESS="iFRSM"

# load machine local bash_profile
[ -f "$HOME/.bash_profile.local" ] && source "$HOME/.bash_profile.local"

# load ~/.bash_login sequential
[ -f "$HOME/.bash_login" ] && source "$HOME/.bash_login"

# vim: sw=2 et
