#!/usr/bin/bash

# ===============================================
# Session Startup Configuration
# ===============================================

# load machine local file
test -f "$HOME/.bash_login.local" && source "$HOME/.bash_login.local"

# Start Graphical Session or SHELL
if [[ -z "$DISPLAY" && "$XDG_VTNR" -eq 1 && ( -z "$XDG_SESSION_TYPE" || "$XDG_SESSION_TYPE" == tty ) ]]; then
  echo -e -n "\
Select Window Manager or Shell:
> 1) Hyprland [default]
  2) Sway
  3) bash
  4) fish
  5) exit
  *) any executable
>>> "
  read -r choice

  # set default wm as the first candidate
  if test -z "$choice"; then
    choice=1
  fi

  # exec shell or exit
  case $choice in
    1|[Hh]yp*)
      wm="Hyprland"
      ;;
    2|sway)
      wm="sway"
      ;;
    3|bash|sh)
      exec bash
      ;;
    4|fish)
      exec fish
      ;;
    5)
      exit 0
      ;;
    *)
      wm="$choice"
      ;;
  esac

  if [[ "$wm" =~ [Hh]yp* ]]; then
    wm="Hyprland"
  fi

  # set gtk theme
  export GTK_THEME=Adwaita:dark

  # set qt theme
  export QT_STYLE_OVERRIDE=kvantum
  export QT_QPA_PLATFORMTHEME=kvantum

  # set input method
  export XMODIFIERS=@im=fcitx
  export GTK_IM_MODULE=fcitx
  export QT_IM_MODULE=fcitx
  export GLFW_IM_MODULE=fcitx

  # Start wayland session
  if [[ "$wm" =~ (Hyprland|sway|weston) ]]; then
    # set xdg env var
    export XDG_SESSION_TYPE=wayland

    # set qt backend
    export QT_QPA_PLATFORM=wayland

    # set firefox use wayland default
    export MOZ_ENABLE_WAYLAND=1

    # set pipewire vaapi driver
    export GST_VAAPI_ALL_DRIVERS=1

    # set xdg env vars
    export XDG_CURRENT_DESKTOP="$wm"
    export XDG_SESSION_DESKTOP="$wm"
    systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP

    # wlroots setting
    if [ "$wm" = Hyprland ]; then
      export WLR_RENDERER=vulkan  # break proton and gamescope
    fi
    #export WLR_DRM_NO_ATOMIC=1  # prevent flickering?
    export WLR_DRM_NO_MODIFIERS=1  # prevent flickering

    # set cursor
    export XCURSOR_THEME='Sweet-cursors'
    export XCURSOR_SIZE=26
    export GTK_USE_PORTAL=1

    # start session
    exec "$wm"
  else  # maybe directly selected executable
    exec "$wm"
  fi
fi

# load bashrc
test -f "$HOME/.bashrc" && source "$HOME/.bashrc"

# vim: sw=2 et
