#!/usr/bin/bash

# ============================================
# Environment Variables
# ============================================

# Setting $PATH
add_path() {
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      path=("$1" $path)
  esac
}

export PATH="$HOME/.local/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
if type rustc &>/dev/null; then
  export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi
if type sccache &>/dev/null; then
  export RUSTC_WRAPPER=$(which sccache)
fi

# Add user specific bin dir
export PATH="$HOME/bin:$PATH"

# set default programs as nvim
if type nvim &>/dev/null; then
  export EDITOR=nvim
  export MANPAGER="nvim +Man! -u ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/manrc"
fi

# Set less variables
export LEFF="-iFRS"
export SYSTEMD_LESS="iFRSM"

# load machine local bash_profile
[ -f $HOME/.bash_profile.local ] && source $HOME/.bash_profile.local

# load ~/.bash_login sequencial
[ -f $HOME/.bash_login ] && source $HOME/.bash_login

# vim: sw=2 et
