#!/usr/bin/bash

### Start fish if login shell on tty
if type fish &>/dev/null && shopt -q login_shell; then
  exec fish
fi


### Load local settings
test -f "${HOME}/.bashrc.local" && source "${HOME}/.bashrc.local"

### Prompt
# use startship only on graphical session
if [ -n "$DISPLAY" ] && type starship &>/dev/null; then
  eval "$(starship init bash)"
fi

# vim: sw=2 et ft=bash
